\documentclass{article}
<<eval=FALSE,echo=FALSE>>=
##Make sure these packages are installed before trying to compile
install.packages(c("ggplot2", "reshape2","gridExtra","RColorBrewer","knitr","beeswarm","UsingR","gapminder","xlsx"))
source("http://www.bioconductor.org/biocLite.R")
biocLite("BiocStyle")
@



<<knitr, echo=FALSE, results="hide">>=
library("knitr")
opts_chunk$set(tidy=FALSE,dev="png",fig.show="as.is",
               fig.width=10,fig.height=6,
               message=FALSE,eval=TRUE,warning=FALSE,echo=TRUE)
@ 

<<style, eval=TRUE, echo=F, results="asis">>=
BiocStyle::latex()
@
\usepackage{ifthen} 
\usepackage{xcolor,colortbl}
\newboolean{includethis} 
\setboolean{includethis}{true} 
\newcommand{\ifinclude}[1]{\ifthenelse{\boolean{includethis}}{#1}{}} 


\begin{document}



\section{Appendix}

\subsection{Fun datasets to play with}

\subsubsection{Elderton and Pearson's (1910) data on drinking and wages}

In 1910, Karl Pearson weighed in on the debate, fostered by the temperance movement, on the evils done by alcohol not only to drinkers, but to their families. The report "A first study of the influence of parental alcholism on the physique and ability of their offspring" was an ambitious attempt to the new methods of statistics to bear on an important question of social policy, to see if the hypothesis that children were damaged by parental alcoholism would stand up to statistical scrutiny.

Working with his assistant, Ethel M. Elderton, Pearson collected voluminous data in Edinburgh and Manchester on many aspects of health, stature, intelligence, etc. of children classified according to the drinking habits of their parents. His conclusions where almost invariably negative: the tendency of parents to drink appeared unrelated to any thing he had measured.

The firestorm that this report set off is well described by Stigler (1999), Chapter 1. The data set DrinksWages is just one of Pearsons many tables, that he published in a letter to The Times, August 10, 1910.

<<>>=
library(HistData)
data("DrinksWages")
head(DrinksWages)
boxplot(wage~class,data=DrinksWages)
par(mfrow=c(2,2))
plot(aov(wage~class,data=DrinksWages))
summary(aov(wage~class,data=DrinksWages))
with(DrinksWages, plot(wage, sober/n, col=c("blue","red","green")[class]))

# fit logistic regression model of sober on wage
mod.sober <- glm(cbind(sober, n) ~ wage, family=binomial, data=DrinksWages)
summary(mod.sober)
op <- par(mfrow=c(2,2))
plot(mod.sober)
@




\subsubsection{Wellbeing}

http://prcweb.co.uk/lab/what-makes-us-happy/

<<>>=
library(UsingR)
data("wellbeing")
head(wellbeing)
mod <- lm(Well.being ~ GDP,data=wellbeing)
summary(mod)
par(mfrow=c(2,2))
plot(mod)
@

<<>>=
plot(wellbeing[,c(3,2)])
abline(mod)
@

\subsubsection{Chick Weights}

Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. Their weights in grams after six weeks are given along with feed types.

<<>>=
require(stats); require(graphics)
boxplot(weight ~ feed, data = chickwts, col = "lightgray",
    varwidth = TRUE, notch = TRUE, main = "chickwt data",
    ylab = "Weight at six weeks (gm)")
anova(fm1 <- lm(weight ~ feed, data = chickwts))
opar <- par(mfrow = c(2, 2), oma = c(0, 0, 1.1, 0),
            mar = c(4.1, 4.1, 2.1, 1.1))
plot(fm1)
par(opar)
@


\subsubsection{Gap Minder Data}

Acknowledgement: http://www.analyticsforfun.com/2014/06/performing-anova-test-in-r-results-and.html

The gapminder R package provides a data frame of life expectancies for various countries, along with continent assignments
<<>>=
library(gapminder)
data(gapminder)
head(gapminder)
@

We can get other risk factors of interest from the gapminder website
<<eval=FALSE>>=
download.file("http://spreadsheets.google.com/pub?key=phAwcNAVuyj0Zbn8wVYsEHQ&output=csv",destfile = "newBreastCancerCases.csv")
download.file("http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGJqTDRfNHBWODJMRWlZaVhNclhNZXc&output=csv",destfile = "alcohol.csv")
download.file("http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHBzUVVSMDlTX1ZCUnNJQ3ZFdkFXVFE&output=csv",destfile = "bloodPressure.csv")
download.file("http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGt0elo2dzJMVVQ3WmFGSmdhc09LRlE&output=csv",destfile = "bodyMassIndex.csv")
download.file("http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGJHcHZkSUdBcU56aS1OT3lLeU4tRHc&output=csv",destfile = "cholesterol.csv")
download.file("http://spreadsheets.google.com/pub?key=thortPEzDn2xc_5bU255mPA&output=csv",destfile="smoking.csv")
@


<<>>=
library(dplyr)

newCases <- read.csv("newBreastCancerCases.csv")

newCases <- newCases %>% rename(country = Breast.Female.Incidence,NewCasesOfBreastCancerIn2002 = X2002) %>% 
            select(country, NewCasesOfBreastCancerIn2002) %>% tbl_df()

alcohol <- read.csv("alcohol.csv") %>% rename(country = X,AlcoholComsumption=X2005) %>% 
          select(country, AlcoholComsumption) %>% tbl_df()

bloodPressure <- read.csv("bloodPressure.csv") %>% rename(country = SBP.female..mm.Hg...age.standardized.mean, BloodPressure = X2002) %>% 
                select(country, BloodPressure) %>%  tbl_df()

bodyMass <- read.csv("bodyMassIndex.csv") %>% rename(country = Country, BodyMassIndex = X2002) %>% 
            select(country,BodyMassIndex) %>% tbl_df()
      
cholestorol <- read.csv("cholesterol.csv") %>% rename(country = TC.female..mmol.L...age.standardized.mean, Cholestorol = X2002) %>% 
            select(country, Cholestorol) %>% tbl_df()

smoking <- read.csv("smoking.csv") %>% rename(country = Prevalence.of.current.tobacco.use.among.adults....15.years......female, Smoking = X2002) %>% 
          select(country, Smoking)

gapminder <- gapminder %>% filter(year == 2002) %>% tbl_df()

breastCancerFactors <- inner_join(gapminder,newCases) %>% 
                      inner_join(alcohol) %>% 
                      inner_join(bloodPressure) %>% 
                      inner_join(bodyMass) %>% 
                      inner_join(cholestorol) %>% 
                      inner_join(smoking)
breastCancerFactors

write.csv(breastCancerFactors,file="globalBreastCancerRisk.csv",quote=FALSE,row.names = FALSE)

breastCancerFactors %>% group_by(continent) %>% summarise(mean(NewCasesOfBreastCancerIn2002))

breastCancerFactors %>% ggplot(aes(x=continent,y=NewCasesOfBreastCancerIn2002)) + geom_boxplot()

@

\subsubsection{Chopstick Effectiveness}

<<>>=
csticks <- read.csv("http://blog.yhathq.com/static/misc/data/chopstick-effectiveness.csv")
head(csticks)
boxplot(Food.Pinching.Effeciency~Chopstick.Length,data=csticks)
summary(aov(Food.Pinching.Effeciency~Chopstick.Length,data=csticks))
@

\subsubsection{Effect of LSD on mathematical ability}

http://blog.yhathq.com/posts/7-funny-datasets.html

<<>>=
lsd <- data.frame(Drugs = c(1.17,2.97,3.26,4.69,5.83,6,6.41), 
                  Score=c(78.93,58.20,67.47,37.47,45.65,32.92,29.98))
mod <- lm(Score~Drugs,data=lsd)
summary(mod)
plot(Score~Drugs,data=lsd)
abline(mod)
@

\subsubsection{Duration of urination does not change with body size}

An \href{http://www.improbable.com/ig/winners/}{\color{blue}{ignoble prize winner}} from 2015. The raw data from this study are provided in a table in (hnngh) pdf format. 


\end{document}